name: Portfolio Projects

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch repos
        run: |
          curl -s https://api.github.com/users/TON_USERNAME/repos?sort=updated > repos.json

      - name: Generate portfolio
        run: |
          echo "" > projects.md

          cat repos.json | jq -r '
          .[] 
          | select(.fork == false) 
          | "### 🚀 \(.name)
<p align=\"center\">
  <a href=\"\(.html_url)\">
    <img src=\"https://opengraph.githubassets.com/1/\(.full_name)\" width=\"500\" />
  </a>
</p>

🧠 Langage : \(.language // "Non défini")  
⭐ Stars : \(.stargazers_count)  

📄 \(.description // "Pas de description")

---
"' >> projects.md

      - name: Inject into README
        run: |
          awk '/<!--START_SECTION:projects-->/ {print; system("cat projects.md"); skip=1; next} 
               /<!--END_SECTION:projects-->/ {skip=0} 
               !skip' README.md > README.tmp

          mv README.tmp README.md

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "update portfolio"
          git push
