name: 💬 Dev-QuoteDay

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Dev Quote in README
        uses: shravan20/github-readme-quotes@v1.0.4
